name: Publish to Docker
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Add your test steps here if needed...
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          username: userlerueda
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io         
      - name: Build container
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/userlerueda/publish-packages:latest
          push: true
